### ISSUE TITLE
矿层装扮引导报错（内附错误日志）

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#1013]
NullReferenceException: Object reference not set to an instance of an object
TouchSureSetDecorationButtonStep.StepProcess () (at Assets/Scripts/Data/Education/DataStruct/Guide/GuideStep/WeaponCommonStep.cs:161)
GuideStep.UpdateStatus () (at Assets/Scripts/Data/Education/DataStruct/Guide/GuideStep/GuideStep.cs:157)
GuideData.UpdateStatus () (at Assets/Scripts/Data/Education/DataStruct/Guide/GuideData.cs:417)
GuideDataHandler.UpdateGuideStepStatus () (at Assets/Scripts/Data/Education/Singleton/GuideDataHandler.cs:637)
GlobalController.UpdateGuideStatus () (at Assets/Scripts/Data/GlobalController/GlobalController+Guide.cs:89)
GlobalController.Update () (at Assets/Scripts/Data/GlobalController/GlobalController.cs:402)

**Comment by aoxu** [comment]
已验证～
