### ISSUE TITLE
加了一个联盟又退出，看到推荐联盟界面异常～

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1021]
加了下图中叫DSADAS的联盟，然后退出，推荐联盟界面就多了一个同名的联盟但是没联盟图标
![image](https://user-images.githubusercontent.com/3169925/40415586-cd8cc4ea-5ead-11e8-9e99-c1e1889a3c59.png)

**Comment by Kinderzhang** [comment]
模拟器上没重现， 现在排查可能是网络原因。不过这边也加了逻辑退出的时候会清空原来的推荐不在等网络回调。

**Comment by aoxu** [comment]
已验证～
