### ISSUE TITLE
在Duel 界面中，PVE的离线奖励可以多次收取

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#1038]
（点击PVE栏目的get按钮收取离线奖励后，会遗留约一半的金钱/经验蛋，并且可以再次收取；（单次收取的数值正常，但由于可以多次收取的缘故，可获得的金币/经验蛋数目，大大超出正常数目））

收取之前的情况
![screenshot_2018-05-25-16-31-54-608_com peakx duel](https://user-images.githubusercontent.com/36027961/40534753-aab67b54-6039-11e8-9d8f-85699441489a.png)

收取之后的情况；（金币正常增加了，但界面上还有可收取的离线奖励）
![screenshot_2018-05-25-16-32-05-553_com peakx duel](https://user-images.githubusercontent.com/36027961/40534747-a4940732-6039-11e8-8744-91f16aa61c04.png)

**Comment by aoxu** [comment]
已验证～
