### ISSUE TITLE
矿层装扮优化项目需要修复

### ISSUE THREAD

**Issue by Zimering** [aoxu/TradeAndDuel#1047]
1.矿层装扮，首先解锁的统一排在没有解锁的前面
2.然后消耗金币购买的矿层装扮要放在消耗美元购买的矿层装扮前面
3.之后不能再购买的矿层装扮，灰掉以后要排到最下面去
4.另外limit 后面的 2/2 前面的数字不需要增加颜色

**Comment by aoxu** [comment]
已验证～
