### ISSUE TITLE
牛仔分配界面CD文案应该是Cooldown，CD是缩写术语，玩家不一定都能看懂～

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1214]
![image](https://user-images.githubusercontent.com/3169925/41850141-14455cea-78b6-11e8-9671-08d582310456.png)

**Comment by WinsonG** [comment]
key:
cd: {0}

**Comment by aoxu** [comment]
文案改了，不生效~

**Comment by aoxu** [comment]
已验证~
