### ISSUE TITLE
玩家信息里的总榜奖杯数错误，段位不知道是不是也错了（没法核实）~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1274]
看到奖杯是0，实际上他是现在总榜第1名的玩家，300多杯
![image](https://user-images.githubusercontent.com/3169925/42074872-de64502a-7ba0-11e8-9738-ac40808905b8.png)

**Comment by WinsonG** [comment]
后台返回的数据结构问题，导致解析不到玩家的league和总榜的数值

**Comment by biubiubiu-a** [comment]
在0.14.1修复

**Comment by aoxu** [comment]
已验证~
