### ISSUE TITLE
到达指定段位的成就不生效，我解锁段位时就在bronze rider，应该一开始就是达成的~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1293]
![image](https://user-images.githubusercontent.com/3169925/42311487-8c471c08-8070-11e8-9836-67c6f3667704.png)

**Comment by Zimering** [comment]
Leageu第一个成就条件是抵达League1-2，不是一开始就解锁，这个条件要展示出来@Kinder，其他的League成就不需要，这里文案展示要改一下逻辑
