### ISSUE TITLE
Eli：好友邀请的链接，能否用短链接？

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1425]
CLICK THIS LINK TO MAKE FRIEND WITH ME IN WILD WEST!
https://tafapkdev.weedo.hk/download?action=inviteFriend&id=1772519704

需要调研一下短链接生成的API，如果实现成本高的话，放到下个版本优化~

**Comment by cokeTsang** [comment]
成本高，下版本再安排

**Comment by aoxu** [comment]
排进版本计划~
