### ISSUE TITLE
升星材料没有展示空闲的牛仔

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1462]
![2f1be72a30fe68e8d455376c595a85ec](https://user-images.githubusercontent.com/23623396/42611624-93964318-85c9-11e8-98a2-a01777f46b98.jpg)
![97108e5200881f0ffca96055d8b66b48](https://user-images.githubusercontent.com/23623396/42611625-95ee12ee-85c9-11e8-85a3-7c289ab230ce.jpg)
![5768ef587dea53c9dbba06cdbcc19441](https://user-images.githubusercontent.com/23623396/42611626-96cf15f0-85c9-11e8-9b4e-affda0243ad6.jpg)

队伍明明有一只青蛙 不在矿层上也不在战斗队列里 但是升星材料里一只牛仔都看不到

**Comment by aoxu** [comment]
已验证~
