### ISSUE TITLE
League打对手，点击对方的头像可以看到对方的队伍有武器，进入战中就没有武器了。

### ISSUE THREAD

**Issue by nearth** [aoxu/TradeAndDuel#1475]
![image](https://user-images.githubusercontent.com/23623474/42732385-4a14f0a4-8853-11e8-8fff-3025f5a37eff.png)
![image](https://user-images.githubusercontent.com/23623474/42732388-4da5a8d0-8853-11e8-861c-8da47d05fba8.png)

**Comment by Kinderzhang** [comment]
因为武器装备数值修改，导致replay数据结构改过了。现在只清除了玩家replay部分，并没有清除携带牛仔之类，就会出现过这样的情况。
