### ISSUE TITLE
Galaxy S7、系统9.0无法正常打开游戏

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1486]
由玩家提出的，具体在哪个界面无法打开有待进一步沟通。

**Comment by cqnature** [comment]
![image](https://user-images.githubusercontent.com/4083867/42742800-9dbbf7aa-88f0-11e8-8e6f-623be5b98503.png)
用户已经自行解决问题了，而且他的系统应该是8.0。
![image](https://user-images.githubusercontent.com/4083867/42742813-be0c99d8-88f0-11e8-8d67-7d4c8a037d65.png)
