### ISSUE TITLE
普通订单的UI展示获得的经验和金币字体是放大的，非必现但很常见~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1491]
![image](https://user-images.githubusercontent.com/3169925/42864045-abc196cc-8a97-11e8-9901-90bb4a0045f3.png)
![image](https://user-images.githubusercontent.com/3169925/42864072-be4c8842-8a97-11e8-8def-9e2b1c48bbdc.png)

**Comment by WinsonG** [comment]
改了一点逻辑规避,不好重现,之后再看看有没有再现
