### ISSUE TITLE
dev版本，牛仔满级时点击快捷升级到升星界面再返回主界面也会弹牛仔养成礼包。按需求不应该弹。

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1495]

**Comment by WinsonG** [comment]
<img width="296" alt="604c05a1-3a72-4b03-828f-e335135cdd2e" src="https://user-images.githubusercontent.com/31625653/42931489-6c2c195c-8b72-11e8-9d6d-2e642216c4a1.png">
