### ISSUE TITLE
玩家邀请他妻子玩我们的游戏，但他没有收到奖励。 

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1524]
![0fd88e322bd09d980763c7c6ee7cd58d](https://user-images.githubusercontent.com/23623396/43178243-01ad7fd0-8fff-11e8-814e-5eb4db5405ae.jpg)

**Comment by aoxu** [comment]
玩家A邀请玩家B加为好友，判断是否能得到奖励的逻辑优化为：
1.在玩家A点击发送邀请时，记录生成邀请链接的时间。
2.在玩家B注册时，现在已经记录了注册时间。
3.玩家B使用A的邀请链接打开游戏，对比A的生成链接时间和B的注册时间，如果注册时间在生成链接时间之后，就算是邀请成功。不用判断玩家A和B在游戏内是否已经是好友，去掉这个旧逻辑，这样就可以解决FB好友的异常。
4.玩家A首次邀请成功，且B也是首次接受邀请成功，A和B就都有奖励。
5.玩家A非首次邀请成功，A没有奖励，但只要B是首次接受邀请成功，B就有奖励。
因为玩家A有可能把邀请链接发给很多人，都邀请成功了的话，A只能拿到一份奖励，而被邀请的人应该每人也能拿到一份奖励。
6.玩家B如果不是首次接受邀请，B不再获得奖励。避免有人接受多个邀请来获得多份奖励。
