### ISSUE TITLE
总榜胜利后挂了

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1580]
![a72d8728b781605caec630da0bb7eb27](https://user-images.githubusercontent.com/23623396/43682572-5bc244e2-98ab-11e8-81d8-7ac95100f473.jpg)
![42f203f477974325ef60e84d6d7e29b6](https://user-images.githubusercontent.com/23623396/43682573-62623758-98ab-11e8-9242-f8d5afbecf6b.jpg)

**Comment by Kinderzhang** [comment]
统计崩溃了引起的
