### ISSUE TITLE
合成系统解锁引导，切到合成系统界面卡死，全屏点击无响应~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1610]
![image](https://user-images.githubusercontent.com/3169925/43764195-5ce33ac4-9a5f-11e8-81d6-225b8fd82e2c.png)

**Comment by cqnature** [comment]
这个暂时是因为切换环境或通过测试工具切换账号的时候，之前账号的本地数据还缓存着导致的问题。不用修复。
