### ISSUE TITLE
解锁food订单展示不正常，完成了一张之后展示恢复正常

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1662]
![d7c0dfef685a2fa5726d093136725a0e](https://user-images.githubusercontent.com/23623396/44013716-d6296298-9ef9-11e8-859c-e5ab40fae74a.jpg)

**Comment by cqnature** [comment]
解锁配置问题，exchangeTrade的解锁条件和订单槽位解锁条件不一致导致的。
