### ISSUE TITLE
testing包，矿层出现的图腾点了没反应~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1715]
![image](https://user-images.githubusercontent.com/3169925/44321908-4036ca80-a47d-11e8-8a00-9170529b7e33.png)
之后切到订单界面，完成了全部订单，领取订单宝箱之后全屏变暗（似乎有蒙层），全屏点击无响应~
![image](https://user-images.githubusercontent.com/3169925/44321927-60ff2000-a47d-11e8-928e-e36f701226ce.png)

**Comment by WinsonG** [comment]
配置只配到20级

**Comment by aoxu** [comment]
已验证~
