### ISSUE TITLE
统计后台目前发现的明显问题汇总2018-9-7 23:43

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1837]
都是小问题，不紧急~

1.新旧后台，今天（9月7日）注册用户数不一致，所有国家 Android。
新后台比旧后台少3个，截图如下（上面是旧，下面是新）
同理DAU也是少3个，应该是少了同样的3个人。
![image](https://user-images.githubusercontent.com/3169925/45229281-03315b80-b2f8-11e8-830f-1d94c3ebc6b2.png)
![image](https://user-images.githubusercontent.com/3169925/45229292-0a586980-b2f8-11e8-8cc2-29f9eb7ec7a6.png)

2.旧后台的“注册”tab，激活到注册流程的最后一步，FB登录成功+guest login成功 加起来才463人，旧后台此时注册人数471人，少了8个人。当然有可能是对应步骤上报失败了，为了以防万一还是排查一下，是少了哪8个，这8个人的数据是否有异常。
![image](https://user-images.githubusercontent.com/3169925/45229480-7dfa7680-b2f8-11e8-92d0-f0d8fa6756a1.png)
![image](https://user-images.githubusercontent.com/3169925/45229489-83f05780-b2f8-11e8-8b34-0a99dc5668f1.png)

**Comment by cokeTsang** [comment]
1. 新统计后台注册日志数据丢失了三条，暂时没找到问题，服务器也没有相关错误日志，后面持续观察。

**Comment by cokeTsang** [comment]
2. 步骤人数上报较少，这里再重新做下测试看下是否存在其他问题。
