### ISSUE TITLE
邀请加为好友功能，奖励判断逻辑优化~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1854]
玩家A邀请玩家B加为好友，判断是否能得到奖励的逻辑优化为：
1.在玩家A点击发送邀请时，记录生成邀请链接的时间。
2.在玩家B注册时，现在已经记录了注册时间。
3.玩家B使用A的邀请链接打开游戏，对比A的生成链接时间和B的注册时间，如果注册时间在生成链接时间之后，就算是邀请成功。不用判断玩家A和B在游戏内是否已经是好友，去掉这个旧逻辑，这样就可以解决FB好友的异常。
4.玩家A首次邀请成功，且B也是首次接受邀请成功，A和B就都有奖励。
5.玩家A非首次邀请成功，A没有奖励，但只要B是首次接受邀请成功，B就有奖励。
因为玩家A有可能把邀请链接发给很多人，都邀请成功了的话，A只能拿到一份奖励，而被邀请的人应该每人也能拿到一份奖励。
6.玩家B如果不是首次接受邀请，B不再获得奖励。避免有人接受多个邀请来获得多份奖励。

**Comment by cokeTsang** [comment]
1.没有生成时间这种概念。
2.跟原有FB自动成为好友有冲突的地方主要是点击邀请链接的时候会检查是否两人已经是好友，是的话不会发奖励。已经修改这个逻辑，假若不是好友，会互相添加好友数据。否则跳过直接走剩下判断是否发放建了个的逻辑。
3.现有点击邀请链接一共有四个判断逻辑：
A：点击的邀请好友链接不是自己的
B：邀请方的好友数量未达上限
C：被邀请方好友数量未达上限
D：邀请方会判断手否首次有人接受邀请
E：被邀请方会判断是否首次接受别人的邀请
满足这死个条件，双方才会收到各自对应的奖励。
