### ISSUE TITLE
玩家ID 257144362反馈：V 0.19.0更新后Bug：联盟订单没有满，FILL按钮缩下去了。

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1884]
![image](https://user-images.githubusercontent.com/3169925/45681419-118d3c00-bb70-11e8-98b2-7dc3ad000702.png)

**Comment by Kinderzhang** [comment]
因为配置更改问题， 这些玩家其实已经领过了。 前端做个异常兼容吧··

**Comment by Kinderzhang** [comment]
检查过，本地无法判断数据是否有效能捐赠。  暂时最好就是修复数据
