### ISSUE TITLE
VIP 4升级到VIP 5，没有拿到VIP 5的奖励。

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1920]
之前是VIP 5，拿了VIP 5的奖励。然后我们调整了数值，他就变成了VIP 4，他昨天付费了到了VIP 5，就没有拿到VIP 5的奖励了。
![355f52a78efe4c4509f96518a7ff6540](https://user-images.githubusercontent.com/23623396/46063573-d27a6e80-c19f-11e8-90c9-f6eb48d86939.jpg)

**Comment by cokeTsang** [comment]
成就领取无法再次领取。
