### ISSUE TITLE
统计后台，付费状态数据准确性需要确认~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1961]
注册2天到18级，需要确认下数据准确性，其他关联的状态数据也需要确认（PVE关卡到第7章，段位到第9个，总榜排名到42，试炼洞穴打到了81关）~
从关联数据看，是符合18级的~
但是从注册时间看，推进过快了~
![image](https://user-images.githubusercontent.com/3169925/46591721-392c5000-caef-11e8-9bb6-fa1c37f1e3ac.png)

**Comment by aoxu** [comment]
查询条件截图
![image](https://user-images.githubusercontent.com/3169925/46592186-e2287a00-caf2-11e8-8db8-dd9a0cfc681f.png)

**Comment by aoxu** [comment]
我尝试导出74670591这一个用户的数据，提示“服务器提出了一个问题”，导出失败~

**Comment by cokeTsang** [comment]
10.09 13:34查了下用户的数据，跟统计一致
"registerTime": 1538649586,
"level": 20,

**Comment by aoxu** [comment]
![image](https://user-images.githubusercontent.com/3169925/46655842-4294e580-cbdf-11e8-9b77-94cba4196354.png)
这个用户按id导出数据失败

**Comment by cokeTsang** [comment]
westshop600031 缺少配置

**Comment by aoxu** [comment]
已经导出数据并排除了作弊可能性，不是异常数据~
