### ISSUE TITLE
统计后台，iOS订阅缺少取消订阅和自动扣款的数据~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1973]
查询条件如图，不可能既没有取消也没有扣款，因为开始了免费试用的人，要么是取消了，要么就会扣款~
![image](https://user-images.githubusercontent.com/3169925/46728689-f8cafe80-ccb5-11e8-9775-5c75fca31cac.png)

**Comment by aoxu** [comment]
真实数据可以在苹果的App Store Connect后台查到，方便对比校验~

**Comment by cokeTsang** [comment]
免费试用人数校验判断的是否出错，因为苹果返回的isTrialPeriod是个字符串，php if判断时认为字符串不为空即为true，导致免费试用人数偏高，也因为错误地判断是试用，所以没有记录原始交易的用户id，导致后续统计无法查找到用户id无法添加统计。这里已经修改提交待后续观察日志。
