### ISSUE TITLE
升级牛仔位置指错

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#1980]
![c17e530f670c51b5f63e2ecb077fdc30](https://user-images.githubusercontent.com/23623396/46845706-1a8bc900-ce0f-11e8-870e-defaa9f9ac14.jpg)

**Comment by Zhangzeduo** [comment]
非强制引导升级牛仔引导  会出现手指错位。
这个问题出现的条件：
1.当按住拖动矿层的时候，会导致引导错位。（这种情况已经解决）
2.当矿层惯性移动当时候，触发引导，这个时候会导致错位，而且导致错位几率比较大。（解决难度较大暂时不修了）

**Comment by Zhangzeduo** [comment]
2.已修复
