### ISSUE TITLE
养成场景重启游戏报错

### ISSUE THREAD

**Issue by Zhangzeduo** [aoxu/TradeAndDuel#1982]
提新的问题时，注意以下几点：
* 说清楚预期行为和实际行为，不要只说其中一种（除非特别明显）。
  * 预期行为可以用“应该是……”句式描述。
  * 实际行为可以用“实际是……”句式描述。
* 提供问题的详细信息，比如：
  * 截图
  * 重现步骤
  * 依赖的账号ID（如果是数据问题）
* 版本信息和环境信息。是线上版本还是测试版本？
  * 测试版本的版本信息，一般用版本号和build号描述。比如`V0.8.2 build 205`。
* 自我检查有没有幺蛾子问题？
  * 是不是过于陈旧的版本？
  * 是不是已经有人提过了？
  * 是不是没开翻墙？（下载热更新/登录FB账号/看广告等功能依赖翻墙）
* 注意在右侧分配责任人和打标签。不打标签的问题将不会有人解决。
  * 标签要区分问题类型是`bug`还是`优化`。
  * 标签要区分优先级是`P0紧急`、`P1尽快`还是`P2一般`。

MissingReferenceException: The object of type 'Transform' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UnityEngine.Transform.get_localScale () (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/TransformBindings.gen.cs:135)
FairyGUI.DisplayObject.SetScale (Single xv, Single yv) (at Assets/Plugins/FairyGUI/Scripts/Core/DisplayObject.cs:468)
FairyGUI.GObject.HandleScaleChanged () (at Assets/Plugins/FairyGUI/Scripts/UI/GObject.cs:1685)
FairyGUI.GObject.SetScale (Single wv, Single hv) (at Assets/Plugins/FairyGUI/Scripts/UI/GObject.cs:634)
FairyGUI.GObject.set_scale (Vector2 value) (at Assets/Plugins/FairyGUI/Scripts/UI/GObject.cs:620)
FairyGUI.GObjectConvert+<DoTweenScale>c__AnonStorey3.<>m__1 (Vector2 x) (at Assets/Plugins/Scripts/GameLib/Extensions/FairyGUI/GObject+Convert.cs:40)
DG.Tweening.Plugins.Vector2Plugin.EvaluateAndApply (VectorOptions options, DG.Tweening.Tween t, Boolean isRelative, DG.Tweening.Core.DOGetter`1 getter, DG.Tweening.Core.DOSetter`1 setter, Single elapsed, Vector2 startValue, Vector2 changeValue, Single duration, Boolean usingInversePosition, UpdateNotice updateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Plugins/Vector2Plugin.cs:106)
DG.Tweening.Core.TweenerCore`3[UnityEngine.Vector2,UnityEngine.Vector2,DG.Tweening.Plugins.Options.VectorOptions].ApplyTween (Single prevPosition, Int32 prevCompletedLoops, Int32 newCompletedSteps, Boolean useInversePosition, UpdateMode updateMode, UpdateNotice updateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenerCore.cs:184)
DG.Tweening.Tween.DoGoto (DG.Tweening.Tween t, Single toPosition, Int32 toCompletedLoops, UpdateMode updateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:240)
DG.Tweening.Core.TweenManager.Goto (DG.Tweening.Tween t, Single to, Boolean andPlay, UpdateMode updateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:613)
DG.Tweening.Sequence.ApplyInternalCycle (DG.Tweening.Sequence s, Single fromPos, Single toPos, UpdateMode updateMode, Boolean useInverse, Boolean prevPosIsInverse, Boolean multiCycleStep) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:269)
DG.Tweening.Sequence.DoApplyTween (DG.Tweening.Sequence s, Single prevPosition, Int32 prevCompletedLoops, Int32 newCompletedSteps, Boolean useInversePosition, UpdateMode updateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:239)
DG.Tweening.Sequence.ApplyTween (Single prevPosition, Int32 prevCompletedLoops, Int32 newCompletedSteps, Boolean useInversePosition, UpdateMode updateMode, UpdateNotice updateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:143)
DG.Tweening.Tween.DoGoto (DG.Tweening.Tween t, Single toPosition, Int32 toCompletedLoops, UpdateMode updateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:240)
DG.Tweening.Core.TweenManager.Update (UpdateType updateType, Single deltaTime, Single independentTime) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:436)
DG.Tweening.Core.DOTweenComponent.Update () (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)

**Comment by Kinderzhang** [comment]
逻辑释放问题 已修复
