### ISSUE TITLE
中文语言，总榜的排行榜界面，“你的排名：”文字歪了，没有对齐排名的位置~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#1991]
![image](https://user-images.githubusercontent.com/3169925/46939830-dc560a00-d099-11e8-914e-62a7f85b66da.png)

**Comment by Kinderzhang** [comment]
就是这样的 居中的
![image](https://user-images.githubusercontent.com/22145841/47061947-5c00e780-d206-11e8-9e7a-3aa8f92a4a0b.png)
