### ISSUE TITLE
玩家反馈，iOS线上版本一个龙虾牛仔和一个鸡不见了

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#2099]
id：1543294870

**Comment by cqusyc** [comment]
id:86965

**Comment by cqusyc** [comment]
{"main": {"1": {"id": 1, "exp": 0, "tier": 0, "grade": 1, "level": 1, "mantoId": 1, "configId": 1, "cooldown": 0, "skillIds": [], "effectTime": 0, "armorInstanceId": 1, "weaponInstanceId": 1}, "2": {"id": 2, "exp": 0, "tier": 0, "grade": 1, "level": 3, "mantoId": 2, "configId": 10, "cooldown": 1540773465, "skillIds": [], "effectTime": 1540773465, "armorInstanceId": 2, "weaponInstanceId": 0}, "4": {"id": 4, "exp": 0, "tier": 0, "grade": 1, "level": 1, "mantoId": 4, "configId": 22, "cooldown": 1540773697, "skillIds": [], "effectTime": 1540773697, "armorInstanceId": 0, "weaponInstanceId": 0}, "5": {"id": 5, "exp": 0, "tier": 0, "grade": 1, "level": 5, "mantoId": 5, "configId": 22, "cooldown": 1540773721, "skillIds": [], "effectTime": 1540773721, "armorInstanceId": 0, "weaponInstanceId": 0}, "6": {"id": 6, "exp": 174, "tier": 0, "grade": 3, "level": 20, "mantoId": 6, "configId": 20, "cooldown": 1540774233, "skillIds": {"20": {"level": 1}}, "effectTime": 1540774233, "armorInstanceId": 6, "weaponInstanceId": 4}, "7": {"id": 7, "exp": 37, "tier": 0, "grade": 1, "level": 11, "mantoId": 7, "configId": 17, "cooldown": 1540815527, "skillIds": [], "effectTime": 1540815527, "armorInstanceId": 0, "weaponInstanceId": 0}, "9": {"id": 9, "exp": 0, "tier": 0, "grade": 1, "level": 1, "mantoId": 9, "configId": 22, "cooldown": 1540816022, "skillIds": [], "effectTime": 1540816022, "armorInstanceId": 0, "weaponInstanceId": 0}, "11": {"id": 11, "exp": 0, "tier": 0, "grade": 1, "level": 1, "mantoId": 10, "configId": 17, "cooldown": 1540818110, "skillIds": [], "effectTime": 1540818110, "armorInstanceId": 0, "weaponInstanceId": 0}}, "maxId": 11, "skillRefreshCount": 0}

**Comment by cqusyc** [comment]
原来拥有11只牛仔，现在只有8只。
现有的逻辑中只有吃牛仔的时候才有删除数据操作。
现在也没有吃牛仔的记录。

**Comment by cqusyc** [comment]
综上所述：
1.最大的可能是被吃掉了
2.然后是bug导致的，
最后，这个基本没办法查，如果要确认是否有bug，只有后面加上相关的日志记录。
