### ISSUE TITLE
iOS线上版本玩家反馈

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#2131]
打不死
![image](https://user-images.githubusercontent.com/3169925/48039766-44879f80-e1b1-11e8-96c8-3a845fc7ef98.png)
![image](https://user-images.githubusercontent.com/3169925/48039771-494c5380-e1b1-11e8-96b8-f6762226f900.png)
打了2局竞技场就崩，然后第3个Ticket就丢失了，要手动重启多次来避免崩溃。。。来自内心的请求：竞技场能不能少一点崩溃。
![image](https://user-images.githubusercontent.com/3169925/48039802-6b45d600-e1b1-11e8-8955-3159420d5b7b.png)

**Comment by aoxu** [comment]
有可能内存不够，我这边红米手机也出现过，ticket损失掉了，没得到战利品~

**Comment by Kinderzhang** [comment]
逻辑修复了一版
