### ISSUE TITLE
德语版，获得奖励弹窗标题超框

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#2159]
![image](https://user-images.githubusercontent.com/3169925/48042976-21fc8300-e1bf-11e8-83af-81f88acadfe3.png)

**Comment by aoxu** [comment]
法语版实测未修复~

**Comment by nerodragon** [comment]
德语版也未修复

**Comment by aoxu** [comment]
![image](https://user-images.githubusercontent.com/3169925/48051480-33a25280-e1e0-11e8-9cc3-c74d8d7a80dc.png)
