### ISSUE TITLE
德语一键升级牛仔标题好像没翻译，另外金币和经验蛋的图标不见了

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#2175]
![ef4da7f70300d58f2ad2bd26f74dd30b](https://user-images.githubusercontent.com/23623396/48053360-7e729900-e1e5-11e8-92ab-03e4959f67dc.jpg)

**Comment by aoxu** [comment]
这就是翻译后的~

**Comment by Kinderzhang** [comment]
图片逗号被改变了
