### ISSUE TITLE
（内有截图）启动时要求的权限有点多，是不是广告SDK要求的？注重隐私的用户看到很容易会产生不想继续打开的感觉。

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#256]
![screenshot_2018-01-19-11-24-49-368_com lbe security miui](https://user-images.githubusercontent.com/3169925/35133970-3a56a11a-fd0e-11e7-88f1-4c20a733308d.png)
![screenshot_2018-01-19-11-24-57-716_com lbe security miui](https://user-images.githubusercontent.com/3169925/35133971-3a91ec3e-fd0e-11e7-9908-6216b3be0f2f.png)

**Comment by cqnature** [comment]
都去掉了，在dev-android-0.3.3版本上

**Comment by aoxu** [comment]
已验证～
