### ISSUE TITLE
矿层界面TAB的上方有一条深褐色的图层

### ISSUE THREAD

**Issue by young2151** [aoxu/TradeAndDuel#341]
矿层界面TAB的上方有一条深褐色的图层

**Comment by cqusyc** [comment]
加图片展示

**Comment by cqusyc** [comment]
@young2151

**Comment by young2151** [comment]
![25am vw1a_ y8pfh 5e5i y](https://user-images.githubusercontent.com/35054156/35608674-05724ff4-0695-11e8-8748-bca2b5600bd8.png)
