### ISSUE TITLE
邮箱界面信息重叠问题，需要调整贴图

### ISSUE THREAD

**Issue by cqnature** [aoxu/TradeAndDuel#417]
![27e55deb0fa52d6bb41ffc345cfc6b8e](https://user-images.githubusercontent.com/4083867/35763594-99e8341c-08ea-11e8-8d8d-eff25aa0360f.jpg)
![f2c5b5447061ae119cdd6a51d25b96bc](https://user-images.githubusercontent.com/4083867/35763595-9b572ed4-08ea-11e8-8ac5-997796a7eff3.jpg)

**Comment by aoxu** [comment]
已验证～
