### ISSUE TITLE
红宝石收集了，在Order里面却没有。 V 0.5.0

### ISSUE THREAD

**Issue by nearth** [aoxu/TradeAndDuel#528]
I found a bug or some glitch, So as I start collecting the coin's, red ore's and blue ore's it shows +3 +9 form the mines but when I go to the order board it show's Zero ore's for both the red and the blue.
I don't know what happened but I waited for these ore's and when I taped on them and try to trade they were never added to the storage.

**Comment by aoxu** [comment]
已验证～
