### ISSUE TITLE
0.7.0 道具建筑选中和未选中状态下的图不一样～

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#552]
![screenshot_2018-03-13-11-33-50-239_com peakx dueldev](https://user-images.githubusercontent.com/3169925/37322269-7ccd4418-26b7-11e8-9926-84d0a09997cd.png)
![screenshot_2018-03-13-11-33-59-269_com peakx dueldev](https://user-images.githubusercontent.com/3169925/37322272-7f62a09c-26b7-11e8-8ccd-aab3b0fe6608.png)

**Comment by WinsonG** [comment]
美术给的选中和未选中就是这两种图片

**Comment by aoxu** [comment]
经过与@leon 确认，选中的时候应该才是飘烟的图片，未选中的时候是不飘烟的图片～

**Comment by aoxu** [comment]
已验证～
