### ISSUE TITLE
完成订单，报错

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#583]
ret:500, Error:<h1>500 Internal Server Error</h1><h3>mt_rand(): max(-1) is smaller than min(0) (2)</h3><pre>#0 [internal function]: flight\Engine->handleError(2, 'mt_rand(): max(...', '/data/code/tafl...', 220, Array)
#1 /data/code/taflogicserver/app/logic/TradeLogic.php(220): mt_rand(0, -1)
#2 /data/code/taflogicserver/app/logic/TradeLogic.php(264): TradeLogic->getTradeConfigId(Array)
#3 /data/code/taflogicserver/app/logic/TradeLogic.php(84): TradeLogic->createNewTrade(Array, 3)
#4 /data/code/taflogicserver/app/controllers/TradeController.php(26): TradeLogic->completeTrade(1021, 3)
#5 /data/code/taflogicserver/app/controllers/MainController.php(44): TradeController->Trade_completeTrade()
#6 /data/code/taflogicserver/app/libs/Controller.php(68): MainController->index()
#7 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(197): Controller::__callStatic('index', Array)
#8 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#9 /data/code/taflogicserver/vendor/mikecao/flight/flight/Engine.php(312): flight\core\Dispatcher::execute(Array, Array)
#10 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start()
#11 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#12 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#13 /data/code/taflogicserver/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('start', Array)
#14 /data/code/taflogicserver/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array)
#15 /data/code/taflogicserver/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#16 /data/code/taflogicserver/public/index.php(19): Flight::__callStatic('start', Array)
#17 {main}</pre>
UnityEngine.Debug:LogWarning(Object)
GameHTTP.WebSocketManager:ReceiveSocketMessage(Dictionary`2) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:813)
GameHTTP.WebSocketManager:OnWebSocketMessage(WebSocket, String) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:508)
BestHTTP.WebSocket.WebSocket:<OnInternalRequestUpgraded>m__0(WebSocketResponse, String) (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocket.cs:401)
BestHTTP.WebSocket.WebSocketResponse:BestHTTP.IProtocol.HandleEvents() (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocketResponse.cs:569)
BestHTTP.HTTPManager:OnUpdate() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPManager.cs:607)
BestHTTP.HTTPUpdateDelegator:Update() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPUpdateDelegator.cs:180)

**Comment by aoxu** [comment]
现在也报500～

**Comment by cokeTsang** [comment]
订单池没有可以选取的订单，配置问题，加了逻辑检测。
