### ISSUE TITLE
点击道具商店的tab，然后切换到武器/衣服上，报错（内附UI和错误信息）

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#588]
![](http://ww1.sinaimg.cn/large/006CVySCgy1fpeijxmjjrj30bz0g8wgc.jpg)

NullReferenceException: Object reference not set to an instance of an object
ProductLineData.get_AutoStorage () (at Assets/Scripts/Data/Education/DataStruct/ProductLine/ProductLineData.cs:149)
ProductLineDataHandler.GetAutoStorageLineData (System.String key) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:82)
ProductLineDataHandler.GetTotalAutoStorageCount (System.String key) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:70)
ResourceData.get_count () (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:51)
ResourceData.GetLackCount (Int32 cost) (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:114)
ResourceData.CheckEnough (Int32 cost) (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:109)
ResourceDataHandler.CheckEnough (Int32 id, Int32 cost) (at Assets/Scripts/Data/Education/Singleton/ResourceDataHandler.cs:91)
ObjectDataHandler.CheckEnough (System.Collections.Generic.List`1 objects) (at Assets/Scripts/Data/Education/Singleton/Base/ObjectDataHandler.cs:204)
EducationUI.WeaponCellNode.ReloadResource () (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponCellNode+Main.cs:83)
EducationUI.WeaponCellNode.ReloadData (.EquipmentData data) (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponCellNode+Main.cs:131)
EducationUI.WeaponNode.ListItemRenderer (Int32 index, FairyGUI.GObject obj) (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponNode+List.cs:81)
FairyGUI.GList.HandleScroll1 (Boolean forceUpdate) (at Assets/Plugins/FairyGUI/Scripts/UI/GList.cs:1892)
FairyGUI.GList.HandleScroll (Boolean forceUpdate) (at Assets/Plugins/FairyGUI/Scripts/UI/GList.cs:1754)
FairyGUI.GList.RefreshVirtualList (System.Object param) (at Assets/Plugins/FairyGUI/Scripts/UI/GList.cs:1583)
FairyGUI.GList.set_numItems (Int32 value) (at Assets/Plugins/FairyGUI/Scripts/UI/GList.cs:1421)
EducationUI.WeaponNode.ReloadList () (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponNode+List.cs:54)
EducationUI.WeaponNode.set_Tab (WeaponNodeTab value) (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponNode+List.cs:26)
EducationUI.EducationNode.WeaponShopButtonEvent () (at Assets/Scripts/UI/Component/EducationUI/EducationNode+TabEvent.cs:73)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1 addChain) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:288)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:330)
FairyGUI.EventListener.BubbleCall (System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:194)
FairyGUI.Stage.HandleMouseEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:818)
FairyGUI.Stage.HandleEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:668)
FairyGUI.Stage.InternalUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:510)
FairyGUI.StageEngine.LateUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/StageEngine.cs:23)

**Comment by aoxu** [comment]
已验证～
