### ISSUE TITLE
购买武器/衣服，报错需要重启。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#589]
ret:GOLD_NOT_ENOUGH, Error:
UnityEngine.Debug:LogWarning(Object)
GameHTTP.WebSocketManager:ReceiveSocketMessage(Dictionary`2) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:813)
GameHTTP.WebSocketManager:OnWebSocketMessage(WebSocket, String) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:508)
BestHTTP.WebSocket.WebSocket:<OnInternalRequestUpgraded>m__0(WebSocketResponse, String) (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocket.cs:401)
BestHTTP.WebSocket.WebSocketResponse:BestHTTP.IProtocol.HandleEvents() (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocketResponse.cs:569)
BestHTTP.HTTPManager:OnUpdate() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPManager.cs:607)
BestHTTP.HTTPUpdateDelegator:Update() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPUpdateDelegator.cs:180)

**Comment by aoxu** [comment]
买道具会闪退。

**Comment by JeffreyXsu** [comment]
已完成
