### ISSUE TITLE
更换冷却中的牛仔，牛仔报错。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#616]
NullReferenceException: Object reference not set to an instance of an object
ProductLineData.get_AutoStorage () (at Assets/Scripts/Data/Education/DataStruct/ProductLine/ProductLineData.cs:149)
ProductLineDataHandler.GetAutoStorageLineData (System.String key) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:82)
ProductLineDataHandler.GetTotalAutoStorageCount (System.String key) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:70)
ResourceData.get_count () (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:51)
StorageData.get_current () (at Assets/Scripts/Data/Education/DataStruct/Storage/StorageData.cs:88)
StorageDataHandler.StashCurrentCount () (at Assets/Scripts/Data/Education/Singleton/StorageDataHandler.cs:119)
EducationUI.MantoActivateNode.MantoCollectBtnEvent (FairyGUI.EventContext context) (at Assets/Scripts/UI/Component/EducationUI/Manto/MantoActivateNode+Main.cs:345)
EducationUI.MantoCellNode.CollectEvent (FairyGUI.EventContext context) (at Assets/Scripts/UI/Component/EducationUI/Manto/MantoCellNode+Main.cs:268)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:76)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1 addChain) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:288)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:331)
FairyGUI.EventListener.BubbleCall (System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:194)
FairyGUI.Stage.HandleMouseEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:818)
FairyGUI.Stage.HandleEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:668)
FairyGUI.Stage.InternalUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:510)
FairyGUI.StageEngine.LateUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/StageEngine.cs:23)

**Comment by cqnature** [comment]
因为修改了FairyGUI的库导致的问题

**Comment by JeffreyXsu** [comment]
已修复
