### ISSUE TITLE
提升等级后，提示玩家解锁系统和获得奖励的界面。酒吧解锁时，“battle”的文案没有正常显示；合成系统解锁没有在界面上展示；优化后的界面未上真机（副标题大小、间隔调整等）。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#637]

**Comment by cqnature** [comment]
缺少的文案key
systemBattleTabTitle
systemWeaponTabTitle
systemMatesTabTitle
systemLeagueTitle
systemComplexTitle
weaponTitle
armorTitle
propTitle
system
equip
ore
complex

**Comment by aoxu** [comment]
已验证～
