### ISSUE TITLE
段位直升时，从不获得奖励，改为立即发放段位结算奖励～

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#658]
发放的奖励是旧段位的奖励，相当于提前结算～
在直升时出现弹窗，传递给玩家直升到哪个段位，和获得了什么奖励，弹窗文案与周期结算奖励不一样～
![image](https://user-images.githubusercontent.com/3169925/38020343-8fb36660-32ac-11e8-9649-1e80d36a40fb.png)

**Comment by Zhangzeduo** [comment]
前端已修复
