### ISSUE TITLE
优化项：TAP TAP 打开卡包的时候，希望能通过点击屏幕的任何地方开包（或至少可点击区域大一些）

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#726]
![screenshot_2018-03-30-17-03-17](https://user-images.githubusercontent.com/36027961/38132324-32cfde3c-343d-11e8-8089-dd1934ffb12f.jpg)

**Comment by aoxu** [comment]
现在就是全屏都可以点～
