### ISSUE TITLE
当版本更迭时，玩家无法通过游戏内关联原有的facebook账号

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#730]
![screenshot_2018-03-30-17-39-59](https://user-images.githubusercontent.com/36027961/38133398-9d8c91ee-3441-11e8-854b-06f943f0acbe.jpg)

**Comment by Kinderzhang** [comment]
因为账号被绑定了··你要么新号 要么初始登录的时候使用facebook登录
