### ISSUE TITLE
矿层收矿报错，没有正常收取矿石。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#733]
product line data config is null, lineId: 0, mantoId: 0, configId:0, activated:False, effectTime:0
UnityEngine.Debug:LogErrorFormat(String, Object[])
ProductLineDataHandler:GetAutoStorageLineData(String) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:83)
ProductLineDataHandler:GetTotalAutoStorageCount(String) (at Assets/Scripts/Data/Education/Singleton/ProductLineDataHandler.cs:70)
ResourceData:get_count() (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:72)
ResourceData:GetLackCount(Int32) (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:146)
ResourceData:CheckEnough(Int32) (at Assets/Scripts/Data/Education/DataStruct/Resource/ResourceData.cs:141)
ResourceDataHandler:CheckEnough(Int32, Int32) (at Assets/Scripts/Data/Education/Singleton/ResourceDataHandler.cs:92)
ObjectDataHandler:CheckEnough(List`1) (at Assets/Scripts/Data/Education/Singleton/Base/ObjectDataHandler.cs:222)
EducationUI.WeaponCellNode:ReloadResource() (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponCellNode+Main.cs:92)
EducationUI.WeaponCellNode:<Awake>m__3(NotificationMessage) (at Assets/Scripts/UI/Component/EducationUI/Weapon/WeaponCellNode+Main.cs:77)
GameLib.NotificationCenter.NotificationCenter:Post(String, Object, Object, Boolean) (at Assets/Scripts/Libs/NotificationCenter/NotificationCenter.cs:130)
ResourceDataHandler:UpdateResource(Object) (at Assets/Scripts/Data/Education/Singleton/ResourceDataHandler.cs:139)
FairyGUI.Timers:Update() (at Assets/Plugins/FairyGUI/Scripts/Utils/Timers.cs:210)
FairyGUI.TimersEngine:Update() (at Assets/Plugins/FairyGUI/Scripts/Utils/Timers.cs:272)

**Comment by aoxu** [comment]
已验证～
