### ISSUE TITLE
第一次售卖合成物，售卖了一次以后，点击售卖第二张订单，报错然后重启了

### ISSUE THREAD

**Issue by Zimering** [aoxu/TradeAndDuel#738]
并且继续完成订单，明明是售卖的矿石，弹出的报错提示是complex_not_enough 然后重启

**Comment by Zimering** [comment]
![](http://ww1.sinaimg.cn/mw690/006wqYXMgy1fpvy62gs9fj30u01hcjv1.jpg)

**Comment by Zimering** [comment]
![](http://ww1.sinaimg.cn/mw690/006wqYXMgy1fpvy6d1dwjj30u01hcwgp.jpg)

**Comment by cqnature** [comment]
可能是配置问题，没有再重现。
