### ISSUE TITLE
总榜战斗新手接入逻辑优化，新手匹配的对手，改成用机器人的头像、名字、奖杯数，现在是取了真实玩家的头像、名字、奖杯数～（内详）

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#749]
1.jeffrey说机器人的头像、名字、奖杯数已经配置。
2.原来的打机器人录像逻辑不变。
3.机器人也用配置的头像、名字、奖杯数展示在总榜的排行榜上，避免玩家看不到这些人。

**Comment by cokeTsang** [comment]
1.已经完成。3.成本原因不做
