### ISSUE TITLE
较长时间未上线后，观看广告获得双倍奖励的功能报错：点击按钮后可正常观看广告、广告结束后回到游戏，载入了一会后，报错

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#772]
![2a878379a88c5553769140bc07b697aa](https://user-images.githubusercontent.com/36027961/38289777-79a2f3fa-380a-11e8-9bf3-e71b3959db55.jpg)

**Comment by cqnature** [comment]
看广告时间超过50s导致掉线了，但是不太好修改。下个版本再改
