### ISSUE TITLE
eric提的，打总榜，打那个第一名的出这个了

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#779]
![x 45hcqsckv g y7 qnczbw](https://user-images.githubusercontent.com/3169925/38346927-b24ab916-38ca-11e8-9107-649d43e6c14a.jpg)

**Comment by Kinderzhang** [comment]
这里涉及骨骼动画加载时长问题。就是文件读取时间长短问题。这个放在0.9.0改吧··一时半会不好改

**Comment by aoxu** [comment]
已验证～
