### ISSUE TITLE
升级仓库弹窗，按钮的文案错误~

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#795]
这个弹窗的按钮文案，跟仓库升级的升级按钮文案，应该用不同的key，现在是同一个key（IMMEDIATELY UPGRADE）
应该分别给一下key～
![2f2f1537ab43a6f370c77ac275d28582](https://user-images.githubusercontent.com/3169925/38454910-8e3828c2-3aa2-11e8-88dd-1b6479b2c57f.jpg)

**Comment by WinsonG** [comment]
增加了新的key：move to depot 
原本key的文案要重新配一下

**Comment by aoxu** [comment]
已验证～
