### ISSUE TITLE
V0.8.1 老用户平仓～

### ISSUE THREAD

**Issue by aoxu** [aoxu/TradeAndDuel#808]
金币仓库：金币拥有量砍到不超过金币仓库上限～
矿石仓库：矿石拥有量砍到不超过矿石仓库上限，砍的优先级是，先砍ore1，再砍ore2，依此类推，直到数量符合要求。目的是为了保留稀有矿石，砍掉普通矿石～
合成物仓库：不做变更。

**Comment by cokeTsang** [comment]
用数据修复脚本的方式实现。

**Comment by aoxu** [comment]
老用户数据测试时验证～
