### ISSUE TITLE
没有达到爆仓上限但是提示爆仓了

### ISSUE THREAD

**Issue by nerodragon** [aoxu/TradeAndDuel#835]
![e64c2850eb59751339fc2395981bfe7a](https://user-images.githubusercontent.com/23623396/38594902-450d9070-3d7b-11e8-8ddd-695dc850bbc7.jpg)
![6e97512299c88a2e6ef24c0378e7f1d3](https://user-images.githubusercontent.com/23623396/38594903-465bcd2a-3d7b-11e8-8ef6-0551109b0932.jpg)

**Comment by cqnature** [comment]
可能是正在同步收矿数据中。
