### ISSUE TITLE
V 0.8.2 玩家反馈到订单界面，所有功能都卡住，玩家自称必现。玩家ID：1985728418

### ISSUE THREAD

**Issue by nearth** [aoxu/TradeAndDuel#854]
提新的问题时，注意以下几点：
* 说清楚预期行为和实际行为，不要只说其中一种（除非特别明显）。
  * 预期行为可以用“应该是……”句式描述。
  * 实际行为可以用“实际是……”句式描述。
* 提供问题的详细信息，比如：
  * 截图
  * 重现步骤
  * 依赖的账号ID（如果是数据问题）
* 版本信息和环境信息。是线上版本还是测试版本？
  * 测试版本的版本信息，一般用版本号和build号描述。比如`V0.8.2 build 205`。
* 自我检查有没有幺蛾子问题？
  * 是不是过于陈旧的版本？
  * 是不是已经有人提过了？
  * 是不是没开翻墙？（下载热更新/登录FB账号/看广告等功能依赖翻墙）
* 注意在右侧分配责任人和打标签。不打标签的问题将不会有人解决。
  * 标签要区分问题类型是`bug`还是`优化`。
  * 标签要区分优先级是`P0紧急`、`P1尽快`还是`P2一般`。

**Comment by cqnature** [comment]
用测试环境登录该玩家账号，没有重现。崩溃后台也没有看到和他相关的问题。可以跟进下是否还会重现，如果还会重现可以删了游戏再安装一次，并用facebook账号登录找回数据。

**Comment by aoxu** [comment]
也许是特定设备问题，可以问一下设备信息～
