### ISSUE TITLE
接入的机器人配置了使用道具，实际上没有使用。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#880]
提新的问题时，注意以下几点：
* 说清楚预期行为和实际行为，不要只说其中一种（除非特别明显）。
  * 预期行为可以用“应该是……”句式描述。
  * 实际行为可以用“实际是……”句式描述。
* 提供问题的详细信息，比如：
  * 截图
  * 重现步骤
  * 依赖的账号ID（如果是数据问题）
* 版本信息和环境信息。是线上版本还是测试版本？
  * 测试版本的版本信息，一般用版本号和build号描述。比如`V0.8.2 build 205`。
* 自我检查有没有幺蛾子问题？
  * 是不是过于陈旧的版本？
  * 是不是已经有人提过了？
  * 是不是没开翻墙？（下载热更新/登录FB账号/看广告等功能依赖翻墙）
* 注意在右侧分配责任人和打标签。不打标签的问题将不会有人解决。
  * 标签要区分问题类型是`bug`还是`优化`。
  * 标签要区分优先级是`P0紧急`、`P1尽快`还是`P2一般`。

**Comment by Kinderzhang** [comment]
配置问题 已经修复了

**Comment by JeffreyXsu** [comment]
已完成
