### ISSUE TITLE
点击订单板下面的绿色广告箱子后，弹出广告引导界面；点击下面的watch按钮后，变为loading且游戏无反应（需要强杀）；（翻墙正常开启中）

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#894]
如果是BUG，希望尽快修复
如果不是BUG（例如网络读取原因），希望能通过点击右上角的X,来返回游戏界面；
![screenshot_2018-04-28-15-29-12-942_com peakx duel](https://user-images.githubusercontent.com/36027961/39393583-7d25a098-4af9-11e8-99c2-27b7e5d3f548.png)

**Comment by cqnature** [comment]
和奥哥提的问题是一样的。
