### ISSUE TITLE
联盟订单界面，正上方有一整块灰色区域（应该是缺少贴图），以及“exp”的大小异常，超框了（内有截图）

### ISSUE THREAD

**Issue by suizixiao** [aoxu/TradeAndDuel#940]
![screenshot_2018-05-14-11-35-56-690_com peakx duel](https://user-images.githubusercontent.com/36027961/39977519-178ae27c-576d-11e8-857b-6f88b1ab473c.png)

**Comment by WinsonG** [comment]
灰色是因为上面预留放骨骼动画，exp是当时配置问题
