### ISSUE TITLE
购买矿层装扮，达到限购前，金币不够，美元购买金币后，报错。

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#968]
ret:-4203, Error:
UnityEngine.Debug:LogWarning(Object)
GameHTTP.WebSocketManager:ReceiveSocketMessage(Dictionary`2) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:813)
GameHTTP.WebSocketManager:OnWebSocketMessage(WebSocket, String) (at Assets/Scripts/Libs/Network/WebSocketManager.cs:508)
BestHTTP.WebSocket.WebSocket:<OnInternalRequestUpgraded>m__0(WebSocketResponse, String) (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocket.cs:401)
BestHTTP.WebSocket.WebSocketResponse:BestHTTP.IProtocol.HandleEvents() (at Assets/Best HTTP (Pro)/BestHTTP/WebSocket/WebSocketResponse.cs:569)
BestHTTP.HTTPManager:OnUpdate() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPManager.cs:607)
BestHTTP.HTTPUpdateDelegator:Update() (at Assets/Best HTTP (Pro)/BestHTTP/HTTPUpdateDelegator.cs:180)

**Comment by WinsonG** [comment]
preview后台不会自动拉取配置，导致前后端配置不同
