### ISSUE TITLE
PVE地图进不去了，配置奖励后，显示报错

### ISSUE THREAD

**Issue by JeffreyXsu** [aoxu/TradeAndDuel#993]
NullReferenceException: Object reference not set to an instance of an object
CommonUI.CommonRewardNode.reload (.ObjectData objectData, Int32 count) (at Assets/Scripts/UI/Component/CommonUI/CommonRewardNode+Main.cs:29)
PVEUI.AdventureMapCellNode.reload (.PveChapterData data) (at Assets/Scripts/UI/Component/PVEUI/AdventureMapCellNode+Main.cs:49)
PVEUI.AdventureMapNode.mapItemRenderer (Int32 index, System.Object obj) (at Assets/Scripts/UI/Component/PVEUI/AdventureMapNode+Main.cs:33)
FairyGUI.GList.set_numItems (Int32 value) (at Assets/Plugins/FairyGUI/Scripts/UI/GList.cs:1449)
PVEUI.AdventureMapNode.ConstructFromResource () (at Assets/Scripts/UI/Component/PVEUI/AdventureMapNode+Main.cs:23)
FairyGUI.UIPackage.CreateObject (FairyGUI.PackageItem item, System.Type userClass) (at Assets/Plugins/FairyGUI/Scripts/UI/UIPackage.cs:947)
FairyGUI.UIPackage.CreateObject (System.String resName) (at Assets/Plugins/FairyGUI/Scripts/UI/UIPackage.cs:891)
FairyGUI.UIPackage.CreateObject (System.String pkgName, System.String resName) (at Assets/Plugins/FairyGUI/Scripts/UI/UIPackage.cs:375)
PopupWindow`1[T].OnInit () (at Assets/Scripts/UI/Controller/Popup/PopupWindow.cs:141)
AdventureMapWindow.OnInit () (at Assets/Scripts/UI/Controller/Popup/PVE/AdventureMapWindow.cs:23)
FairyGUI.Window._init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:437)
FairyGUI.Window.__uiLoadComplete () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:431)
BaseUISource.Load (FairyGUI.UILoadCallback callback) (at Assets/Scripts/UI/Controller/Popup/PopupWindow.cs:56)
FairyGUI.Window.Init () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:371)
FairyGUI.Window.__onShown () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:459)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BroadcastEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:359)
FairyGUI.EventListener.BroadcastCall () (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:222)
FairyGUI.Container.AddChildAt (FairyGUI.DisplayObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/Core/Container.cs:149)
FairyGUI.GComponent.ChildStateChanged (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:732)
FairyGUI.GComponent.AddChildAt (FairyGUI.GObject child, Int32 index) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:214)
FairyGUI.GComponent.AddChild (FairyGUI.GObject child) (at Assets/Plugins/FairyGUI/Scripts/UI/GComponent.cs:172)
FairyGUI.GRoot.ShowWindow (FairyGUI.Window win) (at Assets/Plugins/FairyGUI/Scripts/UI/GRoot.cs:91)
FairyGUI.Window.Show () (at Assets/Plugins/FairyGUI/Scripts/UI/Window.cs:181)
PopupManager.ShowWindow (FairyGUI.Window window) (at Assets/Scripts/Data/Common/PopupManager.cs:423)
PVEUI.AdventureNode.mapBtnEvent () (at Assets/Scripts/UI/Component/PVEUI/AdventureNode+Main.cs:117)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/Plugins/FairyGUI/Scripts/Event/EventBridge.cs:78)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1 addChain) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:288)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventDispatcher.cs:331)
FairyGUI.EventListener.BubbleCall (System.Object data) (at Assets/Plugins/FairyGUI/Scripts/Event/EventListener.cs:194)
FairyGUI.Stage.HandleMouseEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:818)
FairyGUI.Stage.HandleEvents () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:668)
FairyGUI.Stage.InternalUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/Stage.cs:510)
FairyGUI.StageEngine.LateUpdate () (at Assets/Plugins/FairyGUI/Scripts/Core/StageEngine.cs:23)

**Comment by aoxu** [comment]
已验证～
